assets:
  sources:
    - assets/css
    - assets/img
    - assets/js
    - node_modules
baseurl: ''
brand: ЛПР Пермь
collections:
  events:
    output: true
    permalink: /events/:year/:month/:day/:slug:output_ext
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:slug:output_ext
collections_dir: collections
description: >-
  Мы выступаем за свободный рынок и государственное невмешательство
  в экономику, за принцип самопринадлежности и самоценности человеческой
  личности.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - assets
  - node_modules
  - package.json
  - package-lock.json
  - scripts
future: true
lang: ru-RU
markdown: kramdown
minima:
  date_format: '%b %-d, %Y'
plugins:
  - jekyll-assets
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap
title: Либертарианская партия России в Пермском крае
title_extra:
  main: Либертарианская партия России
  secondary: в Пермском крае
url: https://lpr-perm.com
