assets:
  sources:
    - assets/css
    - assets/img
    - assets/js
    - node_modules
baseurl: ""
description: Либертарианская партия России в Пермском крае
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
jekyll_compose:
  auto_open: true
  # Does not work
  post_default_front_matter:
    author: Александр Котов
    lang: ru-RU
    redirect_from: /p/XXXXXX.html
lang: ru-RU
logo: /assets/logo.png
markdown: kramdown
minima:
  date_format: "%b %-d, %Y"
permalink: /:year/:month/:day/:slug:output_ext
plugins:
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-seo-tag
show_excerpts: true
title: ЛПР Пермь
url: "https://lpr-perm.com"
