baseurl: ""
description: >-
  Официальный сайт регионального отделения
  Либертарианской партии России в Пермском крае.
jekyll_compose:
  auto_open: true
  # Does not work
  post_default_front_matter:
    author: Александр Котов
    lang: ru-RU
    redirect_from: /p/XXXXXX.html
lang: ru-RU
logo: /assets/logo.png
markdown: kramdown
minima:
  date_format: "%b %-d, %Y"
permalink: /:year/:month/:day/:slug:output_ext
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
show_excerpts: true
title: Либертарианская партия России в Пермском крае
url: "https://lpr-perm.com"
