baseurl: ""
description: >-
  Официальный сайт регионального отделения
  Либертарианской партии России в Пермском крае.
jekyll_compose:
  auto_open: true
  # Does not work
  post_default_front_matter:
    redirect_from: /p/XXXXXX.html
markdown: kramdown
permalink: /:year/:month/:day/:slug:output_ext
plugins:
  - jekyll-feed
  - jekyll-redirect-from
show_excerpts: true
theme: minima
title: Либертарианская партия России в Пермском крае
url: "https://lpr-perm.com"
