baseurl: ""
description: >-
  Официальный сайт регионального отделения
  Либертарианской партии России в Пермском крае.
markdown: kramdown
plugins:
  - jekyll-feed
theme: minima
title: Либертарианская партия России в Пермском крае
url: "https://lpr-perm.com"
