assets:
  sources:
    - assets/css
    - assets/img
    - assets/js
    - node_modules
baseurl: ''
collections:
  posts:
    permalink: /posts/:year/:month/:day/:slug:output_ext
collections_dir: collections
description: Либертарианская партия России в Пермском крае
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - assets
  - node_modules
  - package.json
  - package-lock.json
  - scripts
google_analytics: UA-129460195-1
jekyll_compose:
  auto_open: true
  # Does not work
  post_default_front_matter:
    author: Александр Котов
lang: ru-RU
markdown: kramdown
minima:
  date_format: '%b %-d, %Y'
plugins:
  - jekyll-assets
  - jekyll-seo-tag
show_excerpts: true
title: ЛПР Пермь
url: https://lpr-perm.com
